### PR TITLE
feat: Add symlinks to data files instead of copying

### PR DESCRIPTION
**Pull request by suryatejreddy**
This PR adds a major change (with little code). 
### Current Behavior
We copy the dataset file that the user loads into the `eva_datasets` folder. 

### Change
This PR modifies this behavior to add a symlink from `eva_datasets` to the file on the user's filesystem. In case the user later deletes the file, an appropriate error is thrown. 

### Testing 
- Added test cases for individual and multiple file loads.
- Added test case for testing correct exception thrown if the file is removed from user's system.

### CODE REVIEW

**Review by gaurav274 — COMMENTED** [review]
Can you verify this also fixes https://github.com/georgia-tech-db/eva/issues/563? Thanks!

**Comment by gaurav274** [comment]
Okay, so it does say 0 files loaded. We can discuss, what the behavior should be if some files are missing while loading and selecting. Btw, in this case if no file was loaded, why does it say missing file? Shouldn't it just execute with empty output?

**Comment by suryatejreddy** [comment]
> Okay, so it does say 0 files loaded. We can discuss, what the behavior should be if some files are missing while loading and selecting. Btw, in this case if no file was loaded, why does it say missing file? Shouldn't it just execute with empty output?

I think it says missing file during select because the original dataset file doesn't exist. That is the check that I have implemented as of now. I think if files are missing while loading we should raise an immediate error there.

**Review by gaurav274 — APPROVED** [review]

**Comment by gaurav274** [comment]
Can we merge this PR, or is there anything remaining?

**Pull request merged**
