### PR TITLE
DROP UDF statement support

### PR DESCRIPTION
**Pull request by kaushikravi3**
This PR adds support for the DROP UDF command.

1. Command syntax:
`DROP UDF [IF EXISTS] <UDF_Name>;`
2. If a UDF by the name does not exist:
    - Raise an exception and log an error if "IF EXISTS" is not specified.
    - Log a warning if "IF EXISTS" is specified.
3. Components tested:
    - Parser
    - Statement to operator converter
    - Planner
    - Plan Executor
    - E2E Integration (with error handling)

### CODE REVIEW

**Review by gaurav274 — COMMENTED** [review]
LGTM
- can you also add the command to the readme and documentation

**Comment by kaushikravi3** [comment]
> LGTM
> 
> * can you also add the command to the readme and documentation

Sure, will do

**Comment by kaushikravi3** [comment]
NOTE: The reason coverage has dropped is because of lines in __eq__, __hash__ and __str__ methods of DropUDFStatement class and some logger warning statement in DropUDFExecutor class

**Comment by gaurav274** [comment]
1. You can add unit test cases to verify str, hash, and eq
And lets merge the PR 👍

**Comment by kaushikravi3** [comment]
> 1. You can add unit test cases to verify str, hash, and eq
>    And lets merge the PR 👍

Added a test to improve coverage. Please sign-off if it's ok.

**Review by gaurav274 — APPROVED** [review]

**Pull request merged**
