### PR TITLE
feat: Enable Support for Querying UDF through Logical Type

### PR DESCRIPTION
**Pull request by adarsh2397**
Tagging Discussion: [Support for Querying using UDF Type](https://github.com/georgia-tech-db/eva/discussions/440)

Changes Made:
- Added a file to store the Enum of different UDF Logical Types
- Added methods to get UDF by type in `catalog_manager.py` and `udf_service.py`
- Modified a existing UDF `FastRCNNObjectDetector` and a test `test_show_info_executor`

Pending Tasks:

- [ ] Should we add a check in `CREATE UDF` statement to check if inputs and outputs match?
- [ ] Add test cases to query using the Logical UDF Type instead of the name

### CODE REVIEW

**Comment by xzdandy** [comment]
Can we add an integration test that uses the Logical UDF?

**Comment by adarsh2397** [comment]
> Can we add an integration test that uses the Logical UDF?

Yep. Working on it. Will update on this thread once I push the changes.

**Comment by adarsh2397** [comment]
Added integration tests for using UDF in a simple select query and as part of a LATERAL JOIN. The PR is ready to merge. Not sure why the coverage has dropped though. I tried investigating, but could not find the issue.

**Comment by jarulraj** [comment]
@IshSiva @kaushikravichandran  @gaurav274 Do we need this PR given the recent changes in decorators?

**Pull request closed without merging**
